# Наискорейший спуск на сфере
## Постановка задачи
$$\underset{\| x \|^2 - 1 = 0}{min} f(x) = x^T A x$$


In [1]:
import numpy as np

## В следующей ячейке в первой строке задается матрица квадратичной формы.
### Далее заранее обсчитываются квадрат и куб этой матрицы, задается начальное приближение, потом сразу же проецируется на сферу.

In [8]:
A = np.array([[1., 100., -1.], [100., 100., 0], [-1.,0,1.]])
A_sq = A.dot(A)
A_th = A.dot(A_sq)
x0 = np.array([1., 0., 1.])
x0 = x0 / np.linalg.norm(x0)

In [9]:
print A
print A_sq
print A_th

[[   1.  100.   -1.]
 [ 100.  100.    0.]
 [  -1.    0.    1.]]
[[  1.00020000e+04   1.01000000e+04  -2.00000000e+00]
 [  1.01000000e+04   2.00000000e+04  -1.00000000e+02]
 [ -2.00000000e+00  -1.00000000e+02   2.00000000e+00]]
[[  1.02000400e+06   2.01020000e+06  -1.00040000e+04]
 [  2.01020000e+06   3.01000000e+06  -1.02000000e+04]
 [ -1.00040000e+04  -1.02000000e+04   4.00000000e+00]]


## В следующей ячейке задается функция, которая возвращает значение второй производной целевой функции при выборе шага (см предыдущее письмо)


In [10]:
def F2(x):
    return (x**3 * (-2.*a2*a2t) + x**2 * (-3. * a2 * a1t) + x * (2.*a2t * a0 - 4. * a2 * a0t + 2. * a1 * a1t) + a1t * a0 + 4. * a1 * a0t) / (a2 * x**2 - 2. * x * a1 + a0)**3

In [11]:
x = x0

In [12]:
for i in range(100):
    a0 = x.T.dot(x)
    a1 = x.T.dot(np.dot(A,x))
    a2 = x.T.dot(np.dot(A_sq,x))
    a3 = x.T.dot(np.dot(A_th,x))
    a2t = a2**2 - a3 * a1
    a1t = a3 * a0 - a2 * a1
    a0t = a1**2 - a0 * a2
    """
    print a0
    print a1
    print a2
    print a3
    print '_____'
    print a2t
    print a1t
    print a0t
    """
    if (a2**2 - a3 * a1) != 0:
        print 'case quadr'
        gamma1 = ((a2 * a1 - a3 * a0) + np.sqrt((a2 * a1 - a3 * a0)**2 - (a2**2 - a3 * a1)*(a1**2 - a0 * a2)))/2. / (a2**2 - a3 * a1)
        gamma2 = ((a2 * a1 - a3 * a0) - np.sqrt((a2 * a1 - a3 * a0)**2 - (a2**2 - a3 * a1)*(a1**2 - a0 * a2)))/2. / (a2**2 - a3 * a1)
        gamma_list = []
        for gamma in [gamma1, gamma2]:
            if gamma >=0 and F2(gamma) > 0:
                gamma_list.append(gamma)
        #print 'gamma_list len = ', len(gamma_list)
        if len(gamma_list) > 0:
            final_gamma = gamma_list[np.random.randint(len(gamma_list))]
        else:
            print 'there is no gamma to move. seems to be you are in minimum'
        print 'quadr gamma = ', final_gamma 
        x = (x - final_gamma * np.dot(A, x))/ np.linalg.norm(x - final_gamma * np.dot(A, x))
    if  (a2**2 - a3 * a1) == 0 and (a3 * a0 - a2 * a1) != 0:
        print 'case linear'
        gamma = (a1**2 - a0 * a2)/(a3 * a0 - a2 * a1)
        if gamma > 0 and F2(gamma) > 0:
                x = (x - gamma * np.dot(A, x))/ np.linalg.norm(x - gamma * np.dot(A, x))
        else:
            print 'you got no suitable gamma'
    if (a3 * a0 - a2 * a1) == 0 and (a2**2 - a3 * a1) == 0:
        print 'you got rekt'
        print 'iternum = ', i
        print '(a3 * a0 - a2 * a1)', (a3 * a0 - a2 * a1)
        print '(a2**2 - a3 * a1)', (a2**2 - a3 * a1)
    print 'iter_num = ', i
    print x
print x

case quadr
quadr gamma =  0.00224744871392
iter_num =  0
[ 0.69834339 -0.1569491   0.69834339]
case quadr
quadr gamma =  0.00312043078501
iter_num =  1
[ 0.69616069 -0.30357885  0.65053838]
case quadr
quadr gamma =  0.0104180320991
iter_num =  2
[ 0.72363202 -0.50954826  0.46552902]
case quadr
quadr gamma =  0.0275995544805
iter_num =  3
[ 0.87095657 -0.45147523  0.19391949]
case quadr
quadr gamma =  0.00332952452136
iter_num =  4
[ 0.8532418  -0.49497212  0.16425904]
case quadr
quadr gamma =  0.010032368922
iter_num =  5
[ 0.83887394 -0.53372033  0.10692576]
case quadr
quadr gamma =  0.0266155741511
iter_num =  6
[ 0.85616207 -0.51444343  0.0483164 ]
case quadr
quadr gamma =  0.00337971087093
iter_num =  7
[ 0.8517266  -0.52227446  0.04232247]
case quadr
quadr gamma =  0.0105966345877
iter_num =  8
[ 0.84799758 -0.52909823  0.03090581]
case quadr
quadr gamma =  0.0208603658042
iter_num =  9
[ 0.85072874 -0.5251819   0.02108524]
case quadr
quadr gamma =  0.00423497896616
iter_num =  10

In [13]:
print 'f* = ', x.dot(np.dot(A,x))
print 'x* = ', x
print 'norm check: ', np.linalg.norm(x)

f* =  -61.0923133565
x* =  [ 0.84953307 -0.52735792  0.01368178]
norm check:  1.0


In [64]:
gamma1 = ((a2 * a1 - a3 * a0) + np.sqrt((a2 * a1 - a3 * a0)**2 - (a2**2 - a3 * a1)*(a1**2 - a0 * a2)))/2. / (a2**2 - a3 * a1)
gamma2 = ((a2 * a1 - a3 * a0) - np.sqrt((a2 * a1 - a3 * a0)**2 - (a2**2 - a3 * a1)*(a1**2 - a0 * a2)))/2. / (a2**2 - a3 * a1)
print gamma1
print gamma2

0.129171306613
3.87082869339


In [66]:
print F2(gamma1)
print F2(gamma2)

-1.0921617741
-0.0019277566945


In [72]:
xk1 = x - gamma1 * A.dot(x)


In [73]:
print xk1
print xk1.dot(np.dot(A, xk1))

[ 0.87082869  0.12917131  0.87082869]
1.30839829258
